<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <!-- This runnable sample is intentionally excluded from solution packaging. -->
    <IsPackable>false</IsPackable>
    <WarnOnPackingNonPackableProject>false</WarnOnPackingNonPackableProject>
    <GenerateDocumentationFile>false</GenerateDocumentationFile>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../src/Kypelon.Pdf.AspNetCore/Kypelon.Pdf.AspNetCore.csproj" />
  </ItemGroup>
</Project>
